local probes = import 'probes.libsonnet';

// Define dashboard variables
local memberClusters = [
  'https://api.kflux-fedora-01.84db.p1.openshiftapps.com:6443/',
  'https://api.kflux-ocp-p01.7ayg.p1.openshiftapps.com:6443/',
  'https://api.kflux-prd-rh02.0fk9.p1.openshiftapps.com:6443/',
  'https://api.kflux-prd-rh03.nnv1.p1.openshiftapps.com:6443/',
  'https://api.kflux-rhel-p01.fc38.p1.openshiftapps.com:6443/',
  'https://api.stone-prd-rh01.pg1f.p1.openshiftapps.com:6443/',
  'https://api.stone-prod-p01.wcfb.p1.openshiftapps.com:6443/',
  'https://api.stone-prod-p02.hjvn.p1.openshiftapps.com:6443/',
  'https://api.stone-stage-p01.hpmt.p1.openshiftapps.com:6443/',
  'https://api.stone-stg-rh01.l2vh.p1.openshiftapps.com:6443/',
];
local testPhaseStubs = [
  '__results_measurements_HandleUser_',
  '__results_measurements_createApplication_',
  '__results_measurements_createComponent_',
  '__results_measurements_createIntegrationTestScenario_',
  '__results_measurements_createReleasePlanAdmission_',
  '__results_measurements_createReleasePlan_',
  '__results_measurements_getPaCPullNumber_',
  '__results_measurements_validateApplication_',
  '__results_measurements_validateComponentBuildSA_',  // TODO: Delme later, I was renamed to just __results_measurements_validateComponent_...
  '__results_measurements_validateComponent_',
  '__results_measurements_validateIntegrationTestScenario_',
  '__results_measurements_validatePipelineRunCondition_',
  '__results_measurements_validatePipelineRunCreation_',
  '__results_measurements_validatePipelineRunSignature_',
  '__results_measurements_validateReleaseCondition_',
  '__results_measurements_validateReleaseCreation_',
  '__results_measurements_validateReleasePipelineRunCondition_',
  '__results_measurements_validateReleasePipelineRunCreation_',
  '__results_measurements_validateReleasePlanAdmission_',
  '__results_measurements_validateReleasePlan_',
  '__results_measurements_validateSnapshotCreation_',
  '__results_measurements_validateTestPipelineRunCondition_',
  '__results_measurements_validateTestPipelineRunCreation_',
];
local taskRunStubs = [
  '__results_durations_stats_taskruns__build_apply_tags__',
  '__results_durations_stats_taskruns__build_buildah__',
  '__results_durations_stats_taskruns__build_build_image_index__',
  '__results_durations_stats_taskruns__build_clair_scan__',
  '__results_durations_stats_taskruns__build_clamav_scan__',
  '__results_durations_stats_taskruns__build_coverity_availability_check__',
  '__results_durations_stats_taskruns__build_deprecated_image_check__',
  '__results_durations_stats_taskruns__build_ecosystem_cert_preflight_checks__',
  '__results_durations_stats_taskruns__build_git_clone__',
  '__results_durations_stats_taskruns__build_init__',
  '__results_durations_stats_taskruns__build_push_dockerfile__',
  '__results_durations_stats_taskruns__build_rpms_signature_scan__',
  '__results_durations_stats_taskruns__build_sast_shell_check__',
  '__results_durations_stats_taskruns__build_sast_snyk_check__',
  '__results_durations_stats_taskruns__build_sast_unicode_check__',
  '__results_durations_stats_taskruns__build_show_sbom__',
  '__results_durations_stats_taskruns__build_summary__',
  '__results_durations_stats_taskruns__test_test_output__',
  '__results_durations_stats_taskruns__build_buildah_oci_ta__',
  '__results_durations_stats_taskruns__build_prefetch_dependencies_oci_ta__',
  '__results_durations_stats_taskruns__build_push_dockerfile_oci_ta__',
  '__results_durations_stats_taskruns__build_sast_shell_check_oci_ta__',
  '__results_durations_stats_taskruns__build_sast_snyk_check_oci_ta__',
  '__results_durations_stats_taskruns__build_sast_unicode_check_oci_ta__',
  '__results_durations_stats_taskruns__build_source_build_oci_ta__',
  '__results_durations_stats_taskruns__managed_collect_data__',
  '__results_durations_stats_taskruns__managed_verify_conforma_konflux_ta__',
];


probes.completeDashboard(
  dashboardName='Konflux clusters loadtest single-arch probe results',
  dashboardDescription='Dashboard visualizes Konflux clusters loadtest single-arch probe results. Related Horreum test is https://horreum.corp.redhat.com/test/372 with filter by label `.parameters.options.ComponentRepoUrl ~ nodejs-devfile-sample` and right `__parameters_options_PipelineRepoTemplatingSourceDir`.',
  dashboardUid='Konflux_clusters_loadtest_probe_results',
  testId=372,
  componentRepoUrl='%/nodejs-devfile-sample%',
  templatingDir='SingleArchLike',
  memberClusters=memberClusters,
  testPhaseStubs=testPhaseStubs,
  taskRunStubs=taskRunStubs,
)
